In [ ]:
from google.colab import files
data = files.upload()

Saving badminton_dataset.csv to badminton_dataset.csv


In [ ]:
data

{'badminton_dataset.csv': b'Outlook,Temperature,Humidity,Wind,Play_Badminton\r\nOvercast,Cool,High,Weak,Yes\r\nSunny,Mild,Normal,Strong,No\r\nRain,Mild,Normal,Strong,No\r\nSunny,Cool,High,Weak,Yes\r\nSunny,Cool,High,Strong,No\r\nSunny,Mild,High,Strong,No\r\nRain,Cool,Normal,Strong,No\r\nRain,Cool,High,Strong,No\r\nSunny,Hot,High,Strong,No\r\nSunny,Hot,Normal,Strong,No\r\nOvercast,Mild,High,Strong,No\r\nOvercast,Hot,High,Strong,No\r\nSunny,Mild,High,Weak,Yes\r\nOvercast,Hot,Normal,Strong,No\r\nSunny,Hot,Normal,Weak,Yes\r\nOvercast,Cool,Normal,Strong,No\r\nRain,Cool,High,Weak,No\r\nSunny,Hot,High,Weak,Yes\r\nRain,Hot,High,Weak,No\r\nOvercast,Cool,High,Strong,No\r\nRain,Hot,Normal,Strong,No\r\nRain,Mild,Normal,Weak,No\r\nSunny,Cool,Normal,Weak,Yes\r\nRain,Mild,High,Weak,No\r\nOvercast,Cool,Normal,Weak,Yes\r\nRain,Cool,Normal,Weak,No\r\nRain,Hot,High,Strong,No\r\nOvercast,Hot,Normal,Weak,Yes\r\nOvercast,Mild,High,Weak,Yes\r\nRain,Mild,High,Strong,No\r\nOvercast,Hot,High,Weak,Yes\r\nOvercas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df = pd.read_csv('badminton_dataset.csv')

In [ ]:
df

Outlook Temperature Humidity    Wind Play_Badminton
0   Overcast        Cool     High    Weak            Yes
1      Sunny        Mild   Normal  Strong             No
2       Rain        Mild   Normal  Strong             No
3      Sunny        Cool     High    Weak            Yes
4      Sunny        Cool     High  Strong             No
5      Sunny        Mild     High  Strong             No
6       Rain        Cool   Normal  Strong             No
7       Rain        Cool     High  Strong             No
8      Sunny         Hot     High  Strong             No
9      Sunny         Hot   Normal  Strong             No
10  Overcast        Mild     High  Strong             No
11  Overcast         Hot     High  Strong             No
12     Sunny        Mild     High    Weak            Yes
13  Overcast         Hot   Normal  Strong             No
14     Sunny         Hot   Normal    Weak            Yes
15  Overcast        Cool   Normal  Strong             No
16      Rain        Cool     High    Weak             No
17     Sunny         Hot     High    Weak            Yes
18      Rain         Hot     High    Weak             No
19  Overcast        Cool     High  Strong             No
20      Rain         Hot   Normal  Strong             No
21      Rain        Mild   Normal    Weak             No
22     Sunny        Cool   Normal    Weak            Yes
23      Rain        Mild     High    Weak             No
24  Overcast        Cool   Normal    Weak            Yes
25      Rain        Cool   Normal    Weak             No
26      Rain         Hot     High  Strong             No
27  Overcast         Hot   Normal    Weak            Yes
28  Overcast        Mild     High    Weak            Yes
29      Rain        Mild     High  Strong             No
30  Overcast         Hot     High    Weak            Yes
31  Overcast        Mild   Normal    Weak            Yes
32     Sunny        Cool   Normal  Strong             No
33      Rain         Hot   Normal    Weak             No
34     Sunny        Mild   Normal    Weak            Yes
35  Overcast        Mild   Normal  Strong             No

In [ ]:
# EDA
df.shape

(36, 5)

In [ ]:
df.columns

Index(['Outlook', 'Temperature', 'Humidity', 'Wind', 'Play_Badminton'], dtype='object')

In [ ]:
df.head(10)

Outlook Temperature Humidity    Wind Play_Badminton
0  Overcast        Cool     High    Weak            Yes
1     Sunny        Mild   Normal  Strong             No
2      Rain        Mild   Normal  Strong             No
3     Sunny        Cool     High    Weak            Yes
4     Sunny        Cool     High  Strong             No
5     Sunny        Mild     High  Strong             No
6      Rain        Cool   Normal  Strong             No
7      Rain        Cool     High  Strong             No
8     Sunny         Hot     High  Strong             No
9     Sunny         Hot   Normal  Strong             No

In [ ]:
df.tail(10)

Outlook Temperature Humidity    Wind Play_Badminton
26      Rain         Hot     High  Strong             No
27  Overcast         Hot   Normal    Weak            Yes
28  Overcast        Mild     High    Weak            Yes
29      Rain        Mild     High  Strong             No
30  Overcast         Hot     High    Weak            Yes
31  Overcast        Mild   Normal    Weak            Yes
32     Sunny        Cool   Normal  Strong             No
33      Rain         Hot   Normal    Weak             No
34     Sunny        Mild   Normal    Weak            Yes
35  Overcast        Mild   Normal  Strong             No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Outlook         36 non-null     object
 1   Temperature     36 non-null     object
 2   Humidity        36 non-null     object
 3   Wind            36 non-null     object
 4   Play_Badminton  36 non-null     object
dtypes: object(5)
memory usage: 1.5+ KB


In [ ]:
df.columns

Index(['Outlook', 'Temperature', 'Humidity', 'Wind', 'Play_Badminton'], dtype='object')

In [ ]:
# LABEL ENCODING:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['Outlook'] = le.fit_transform(df['Outlook'])
df['Temperature'] = le.fit_transform(df['Temperature'])
df['Humidity'] = le.fit_transform(df['Humidity'])
df['Wind'] = le.fit_transform(df['Wind'])
df['Play_Badminton'] = le.fit_transform(df['Play_Badminton'])



In [ ]:
df

Outlook  Temperature  Humidity  Wind  Play_Badminton
0         0            0         0     1               1
1         2            2         1     0               0
2         1            2         1     0               0
3         2            0         0     1               1
4         2            0         0     0               0
5         2            2         0     0               0
6         1            0         1     0               0
7         1            0         0     0               0
8         2            1         0     0               0
9         2            1         1     0               0
10        0            2         0     0               0
11        0            1         0     0               0
12        2            2         0     1               1
13        0            1         1     0               0
14        2            1         1     1               1
15        0            0         1     0               0
16        1            0         0     1               0
17        2            1         0     1               1
18        1            1         0     1               0
19        0            0         0     0               0
20        1            1         1     0               0
21        1            2         1     1               0
22        2            0         1     1               1
23        1            2         0     1               0
24        0            0         1     1               1
25        1            0         1     1               0
26        1            1         0     0               0
27        0            1         1     1               1
28        0            2         0     1               1
29        1            2         0     0               0
30        0            1         0     1               1
31        0            2         1     1               1
32        2            0         1     0               0
33        1            1         1     1               0
34        2            2         1     1               1
35        0            2         1     0               0

In [ ]:
df.describe()

Outlook  Temperature   Humidity       Wind  Play_Badminton
count  36.000000    36.000000  36.000000  36.000000       36.000000
mean    1.000000     1.000000   0.500000   0.500000        0.333333
std     0.828079     0.828079   0.507093   0.507093        0.478091
min     0.000000     0.000000   0.000000   0.000000        0.000000
25%     0.000000     0.000000   0.000000   0.000000        0.000000
50%     1.000000     1.000000   0.500000   0.500000        0.000000
75%     2.000000     2.000000   1.000000   1.000000        1.000000
max     2.000000     2.000000   1.000000   1.000000        1.000000

In [ ]:
# DATA CLEANING:
df.isnull()

Outlook  Temperature  Humidity   Wind  Play_Badminton
0     False        False     False  False           False
1     False        False     False  False           False
2     False        False     False  False           False
3     False        False     False  False           False
4     False        False     False  False           False
5     False        False     False  False           False
6     False        False     False  False           False
7     False        False     False  False           False
8     False        False     False  False           False
9     False        False     False  False           False
10    False        False     False  False           False
11    False        False     False  False           False
12    False        False     False  False           False
13    False        False     False  False           False
14    False        False     False  False           False
15    False        False     False  False           False
16    False        False     False  False           False
17    False        False     False  False           False
18    False        False     False  False           False
19    False        False     False  False           False
20    False        False     False  False           False
21    False        False     False  False           False
22    False        False     False  False           False
23    False        False     False  False           False
24    False        False     False  False           False
25    False        False     False  False           False
26    False        False     False  False           False
27    False        False     False  False           False
28    False        False     False  False           False
29    False        False     False  False           False
30    False        False     False  False           False
31    False        False     False  False           False
32    False        False     False  False           False
33    False        False     False  False           False
34    False        False     False  False           False
35    False        False     False  False           False

In [ ]:
df.isnull().sum()

Outlook           0
Temperature       0
Humidity          0
Wind              0
Play_Badminton    0
dtype: int64

In [ ]:
X = df.iloc[:,:4]

In [ ]:
X

Outlook  Temperature  Humidity  Wind
0         0            0         0     1
1         2            2         1     0
2         1            2         1     0
3         2            0         0     1
4         2            0         0     0
5         2            2         0     0
6         1            0         1     0
7         1            0         0     0
8         2            1         0     0
9         2            1         1     0
10        0            2         0     0
11        0            1         0     0
12        2            2         0     1
13        0            1         1     0
14        2            1         1     1
15        0            0         1     0
16        1            0         0     1
17        2            1         0     1
18        1            1         0     1
19        0            0         0     0
20        1            1         1     0
21        1            2         1     1
22        2            0         1     1
23        1            2         0     1
24        0            0         1     1
25        1            0         1     1
26        1            1         0     0
27        0            1         1     1
28        0            2         0     1
29        1            2         0     0
30        0            1         0     1
31        0            2         1     1
32        2            0         1     0
33        1            1         1     1
34        2            2         1     1
35        0            2         1     0

In [ ]:
Y = df.iloc[:, 4].values

In [ ]:
Y

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0])

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=10)

In [ ]:
x_train

Outlook  Temperature  Humidity  Wind
18        1            1         0     1
14        2            1         1     1
1         2            2         1     0
23        1            2         0     1
20        1            1         1     0
22        2            0         1     1
6         1            0         1     0
11        0            1         0     0
34        2            2         1     1
21        1            2         1     1
30        0            1         0     1
19        0            0         0     0
4         2            0         0     0
27        0            1         1     1
10        0            2         0     0
33        1            1         1     1
35        0            2         1     0
8         2            1         0     0
26        1            1         0     0
17        2            1         0     1
16        1            0         0     1
29        1            2         0     0
25        1            0         1     1
28        0            2         0     1
0         0            0         0     1
15        0            0         1     0
9         2            1         1     0

In [ ]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
# NAIVE BAYES USING GAUSSIANNB METHOD:
from sklearn.naive_bayes import GaussianNB
BD = GaussianNB()
BD.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = BD.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[5, 0],
       [0, 4]])

In [ ]:
# NAIVE BAYES USING BERNOULLINB METHOD:
from sklearn.naive_bayes import BernoulliNB
BD1 = BernoulliNB()
BD1.fit(x_train, y_train)

BernoulliNB()

In [ ]:
y_pre = BD1.predict(x_test)
y_pre

array([1, 1, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pre)
cm

array([[5, 0],
       [2, 2]])