In [ ]:
from google.colab import files
data = files.upload()

Saving Customer+List.csv to Customer+List.csv


In [ ]:
data

{'Customer+List.csv': b'Customer ID,Gender,Age,Salary,Purchased\r\n1,Male,19,19000,0\r\n2,Male,35,20000,0\r\n3,Female,26,43000,0\r\n4,Female,27,57000,0\r\n5,Male,19,76000,0\r\n6,Male,27,58000,0\r\n7,Female,27,84000,0\r\n8,Female,32,150000,1\r\n9,Male,25,33000,0\r\n10,Female,35,65000,0\r\n11,Female,26,80000,0\r\n12,Female,26,52000,0\r\n13,Male,20,86000,0\r\n14,Male,32,18000,0\r\n15,Male,18,82000,0\r\n16,Male,29,80000,0\r\n17,Male,47,25000,1\r\n18,Male,45,26000,1\r\n19,Male,46,28000,1\r\n20,Female,48,29000,1\r\n21,Male,45,22000,1\r\n22,Female,47,49000,1\r\n23,Male,48,41000,1\r\n24,Female,45,22000,1\r\n25,Male,46,23000,1\r\n26,Male,47,20000,1\r\n27,Male,49,28000,1\r\n28,Female,47,30000,1\r\n29,Male,29,43000,0\r\n30,Male,31,18000,0\r\n31,Male,31,74000,0\r\n32,Female,27,137000,1\r\n33,Female,21,16000,0\r\n34,Female,28,44000,0\r\n35,Male,27,90000,0\r\n36,Male,35,27000,0\r\n37,Female,33,28000,0\r\n38,Male,30,49000,0\r\n39,Female,26,72000,0\r\n40,Female,27,31000,0\r\n41,Female,27,17000,0\r\n42

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df = pd.read_csv('Customer+List.csv')

In [ ]:
df

Customer ID  Gender  Age  Salary  Purchased
0              1    Male   19   19000          0
1              2    Male   35   20000          0
2              3  Female   26   43000          0
3              4  Female   27   57000          0
4              5    Male   19   76000          0
..           ...     ...  ...     ...        ...
395          396  Female   46   41000          1
396          397    Male   51   23000          1
397          398  Female   50   20000          1
398          399    Male   36   33000          0
399          400  Female   49   36000          1

[400 rows x 5 columns]

In [ ]:
# EDA
df.shape

(400, 5)

In [ ]:
df.columns

Index(['Customer ID', 'Gender', 'Age', 'Salary', 'Purchased'], dtype='object')

In [ ]:
df.head(6)

Customer ID  Gender  Age  Salary  Purchased
0            1    Male   19   19000          0
1            2    Male   35   20000          0
2            3  Female   26   43000          0
3            4  Female   27   57000          0
4            5    Male   19   76000          0
5            6    Male   27   58000          0

In [ ]:
df.tail(6)

Customer ID  Gender  Age  Salary  Purchased
394          395  Female   39   59000          0
395          396  Female   46   41000          1
396          397    Male   51   23000          1
397          398  Female   50   20000          1
398          399    Male   36   33000          0
399          400  Female   49   36000          1

In [ ]:
df.describe()

Customer ID         Age         Salary   Purchased
count   400.000000  400.000000     400.000000  400.000000
mean    200.500000   37.655000   69742.500000    0.357500
std     115.614301   10.482877   34096.960282    0.479864
min       1.000000   18.000000   15000.000000    0.000000
25%     100.750000   29.750000   43000.000000    0.000000
50%     200.500000   37.000000   70000.000000    0.000000
75%     300.250000   46.000000   88000.000000    1.000000
max     400.000000   60.000000  150000.000000    1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer ID  400 non-null    int64 
 1   Gender       400 non-null    object
 2   Age          400 non-null    int64 
 3   Salary       400 non-null    int64 
 4   Purchased    400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [ ]:
# LABEL ENCODING:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

In [ ]:
df

Customer ID  Gender  Age  Salary  Purchased
0              1       1   19   19000          0
1              2       1   35   20000          0
2              3       0   26   43000          0
3              4       0   27   57000          0
4              5       1   19   76000          0
..           ...     ...  ...     ...        ...
395          396       0   46   41000          1
396          397       1   51   23000          1
397          398       0   50   20000          1
398          399       1   36   33000          0
399          400       0   49   36000          1

[400 rows x 5 columns]

In [ ]:
# DATA CLEANING:
df.isnull()

Customer ID  Gender    Age  Salary  Purchased
0          False   False  False   False      False
1          False   False  False   False      False
2          False   False  False   False      False
3          False   False  False   False      False
4          False   False  False   False      False
..           ...     ...    ...     ...        ...
395        False   False  False   False      False
396        False   False  False   False      False
397        False   False  False   False      False
398        False   False  False   False      False
399        False   False  False   False      False

[400 rows x 5 columns]

In [ ]:
df.isnull().sum() # null percentage is zero

Customer ID    0
Gender         0
Age            0
Salary         0
Purchased      0
dtype: int64

In [ ]:
X = df.iloc[:, [2,3]].values
Y = df.iloc[:, 4].values

In [ ]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [ ]:
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=40)

In [ ]:
x_train

array([[    28,  32000],
       [    51,  23000],
       [    46, 117000],
       [    54, 108000],
       [    37,  70000],
       [    34,  72000],
       [    52,  38000],
       [    58, 101000],
       [    31,  66000],
       [    40,  65000],
       [    27,  88000],
       [    39,  73000],
       [    19,  25000],
       [    33,  41000],
       [    34,  43000],
       [    48,  33000],
       [    35,  23000],
       [    42,  80000],
       [    37,  79000],
       [    30,  49000],
       [    48,  35000],
       [    47,  49000],
       [    35,  59000],
       [    35,  38000],
       [    44, 139000],
       [    26,  81000],
       [    22,  81000],
       [    60, 108000],
       [    39,  79000],
       [    45, 131000],
       [    31,  89000],
       [    56, 133000],
       [    39, 134000],
       [    58, 144000],
       [    59,  42000],
       [    42,  73000],
       [    26,  80000],
       [    57,  74000],
       [    29,  43000],
       [    48,  74000],


In [ ]:
y_train

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
# NAIVE BAYES USING GAUSSIANNB METHOD:
from sklearn.naive_bayes import GaussianNB
cus_lt = GaussianNB()
cus_lt.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = cus_lt.predict(x_test)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[63,  3],
       [ 9, 25]])

In [ ]:
# NAIVE BAYES USING BERNOULLINB METHOD:
from sklearn.naive_bayes import BernoulliNB
cus_lt1 = BernoulliNB()
cus_lt1.fit(x_train, y_train)

BernoulliNB()

In [ ]:
y_pred = cus_lt1.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred)
cm1

array([[59,  7],
       [25,  9]])