In [ ]:
from google.colab import files
data = files.upload()

Saving kaggle_-1000.csv to kaggle_-1000.csv


In [ ]:
data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# DAta Processing
df = pd.read_csv('kaggle_-1000.csv')

In [ ]:
df

Unnamed: 0                                              title  \
0             0  COVID-19 Open Research Dataset Challenge (CORD...   
1             1               Animal Crossing New Horizons Catalog   
2             2                        Credit Card Fraud Detection   
3             3                        Netflix Movies and TV Shows   
4             4                    Novel Corona Virus 2019 Dataset   
..          ...                                                ...   
994         994                      Economic Freedom of the World   
995         995                    Zillow Rent Index, 2010-Present   
996         996                   The Interview Attendance Problem   
997         997                          US Population By Zip Code   
998         998                           British Birdsong Dataset   

                       uploaded_by           last_updated  usability  \
0          Allen Institute For AI     Updated 12 days ago        8.8   
1                      Jessica Li    Updated 7 months ago        8.2   
2    Machine Learning Group - ULB     Updated 4 years ago        8.5   
3                   Shivam Bansal    Updated 3 months ago       10.0   
4                             SRK    Updated 6 months ago        9.7   
..                             ...                    ...        ...   
994  Guillermina Sutter Schneider     Updated 3 years ago        7.4   
995                        Zillow     Updated 5 years ago        7.4   
996                VishnuRaghavan     Updated 4 years ago        7.9   
997              US Census Bureau     Updated 5 years ago        8.2   
998                Rachael Tatman     Updated 4 years ago        7.6   

                                 files     size  upvotes   badge  
0     558167 Files (JSON, CSV, other)     14 GB     9710    Gold  
1                      30 Files (CSV)    591 kB     9652    Gold  
2                        1 File (CSV)     69 MB     8712    Gold  
3                        1 File (CSV)      1 MB     6056    Gold  
4                       6 Files (CSV)      9 MB     5679    Gold  
..                                 ...      ...      ...     ...  
994                      1 File (CSV)    413 kB      114  Bronze  
995                     2 Files (CSV)      4 MB      114  Bronze  
996              2 Files (CSV, other)    127 kB      114  Silver  
997                     2 Files (CSV)     30 MB      114  Silver  
998            264 Files (other, CSV)    664 MB      115  Silver  

[999 rows x 9 columns]

In [ ]:
#EDA
df.shape

(999, 9)

In [ ]:
df.columns

Index(['Unnamed: 0', 'title', 'uploaded_by', 'last_updated', 'usability',
       'files', 'size', 'upvotes', 'badge'],
      dtype='object')

In [ ]:
df.head(11)

In [ ]:
df.tail(11)

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
# DATA CLEANING
df.isnull()

In [ ]:
df.isnull().sum() ## NULL VALUE PERCENTAGE IS 0%

In [ ]:
dfs = df.drop(['Unnamed: 0'],axis = 1)

In [ ]:
dfs

In [ ]:
#LABEL ENCODING
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
dfs['badge']=le.fit_transform(dfs['badge'])

In [ ]:
dfs

In [ ]:
df['badge'].unique()

array(['Gold', 'Silver', 'Bronze', 'more_horiz'], dtype=object)

In [ ]:
dfs['badge'].unique()

array([1, 2, 0, 3])

In [ ]:
dfs.describe()

usability      upvotes       badge
count  999.000000   999.000000  999.000000
mean     8.123924   457.679680    1.319319
std      1.622493   789.305502    0.658791
min      1.200000   114.000000    0.000000
25%      7.100000   151.000000    1.000000
50%      8.200000   221.000000    1.000000
75%      9.700000   416.000000    2.000000
max     10.000000  9710.000000    3.000000

In [ ]:
dfs1= dfs.iloc[0:334]
dfs2= dfs.iloc[334:664]
dfs3= dfs.iloc[664:999]

In [ ]:
dfs1

title  \
0    COVID-19 Open Research Dataset Challenge (CORD...   
1                 Animal Crossing New Horizons Catalog   
2                          Credit Card Fraud Detection   
3                          Netflix Movies and TV Shows   
4                      Novel Corona Virus 2019 Dataset   
..                                                 ...   
329                            New York Times Comments   
330                       Armenian Online Job Postings   
331         COVID-19 data from John Hopkins University   
332                                            fer2013   
333                        IMDB data from 2006 to 2016   

                       uploaded_by           last_updated  usability  \
0          Allen Institute For AI     Updated 12 days ago        8.8   
1                      Jessica Li    Updated 7 months ago        8.2   
2    Machine Learning Group - ULB     Updated 4 years ago        8.5   
3                   Shivam Bansal    Updated 3 months ago       10.0   
4                             SRK    Updated 6 months ago        9.7   
..                             ...                    ...        ...   
329             Aashita Kesarwani     Updated 4 years ago        7.1   
330                       Udacity     Updated 4 years ago        5.9   
331             Anthony Goldbloom     Updated 3 hours ago        8.8   
332                   Rohit Verma     Updated 4 years ago        2.9   
333                   PromptCloud     Updated 5 years ago       10.0   

                                 files     size  upvotes  badge  
0     558167 Files (JSON, CSV, other)     14 GB     9710      1  
1                      30 Files (CSV)    591 kB     9652      1  
2                        1 File (CSV)     69 MB     8712      1  
3                        1 File (CSV)      1 MB     6056      1  
4                       6 Files (CSV)      9 MB     5679      1  
..                                 ...      ...      ...    ...  
329                    18 Files (CSV)    503 MB      339      1  
330              3 Files (CSV, other)     15 MB      337      2  
331                    10 Files (CSV)      8 MB      337      1  
332                      1 File (CSV)    101 MB      336      2  
333                      1 File (CSV)    137 kB      336      2  

[334 rows x 8 columns]

In [ ]:
x = np.array(dfs1[['usability','upvotes']])
y = np.array(dfs1['badge'])

In [ ]:
x

In [ ]:
y

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, cross_val_score
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=40)

In [ ]:
x_train

In [ ]:
y_train

# **K - NEAREST NEIGHORS:**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
classifier.score(x_test, y_test)

0.9285714285714286

In [ ]:
y_pred_knn = classifier.predict(x_test)
y_pred_knn

In [ ]:
from sklearn.metrics import confusion_matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)
cm_knn

array([[78,  1],
       [ 5,  0]])

# **SUPPORT VECTOR MACHINES:**

In [ ]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)

SVC()

In [ ]:
svc.score(x_test, y_test)

0.9404761904761905

In [ ]:
Y_predict_svm = svc.predict(x_test)
Y_predict_svm

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm_svm = confusion_matrix(y_test, Y_predict_svm)
cm_svm

array([[79,  0],
       [ 5,  0]])

# **MULTIPLE LINEAR REGRESSION:**

In [ ]:
from sklearn.linear_model import LinearRegression
kaggle_1k =LinearRegression()

In [ ]:
kaggle_1k.fit(x_train,y_train)

LinearRegression()

In [ ]:
kaggle_1k.score(x_test, y_test)


-29.713186567604023

In [ ]:
y_predict = kaggle_1k.predict(x_test)
y_predict

In [ ]:
sns.regplot(x=y_test, y=y_predict, ci=None, color="red")
plt.plot(x_train, kaggle_1k.predict(x_train))
plt.xlabel("usability upvotes")
plt.ylabel("badge")

In [ ]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [ ]:
MAE = mean_absolute_error(y_test,y_predict)
print(MAE)
MSE = mean_squared_error(y_test,y_predict)
print(MSE)
RSME = np.sqrt(MSE)
print(RSME)
LRSME = np.log(RSME)
print(LRSME)
R2 = r2_score(y_test,y_predict)
print(R2)

0.10742650535527176
0.05534790487068902
0.23526135439270304
-1.4470582364626599
0.011304261347894418


# **Naive Bayes:**




In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
# NAIVE BAYES USING GAUSSIANNB METHOD:
from sklearn.naive_bayes import GaussianNB
kag = GaussianNB()
kag.fit(x_train, y_train)

GaussianNB()

In [ ]:
kag.score(x_test, y_test)

0.7380952380952381

In [ ]:
y_pred = kag.predict(x_test)
y_pred

array([1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2])

In [ ]:
from sklearn.metrics import confusion_matrix
cm_naive = confusion_matrix(y_test, y_pred)
cm_naive

array([[59, 20],
       [ 2,  3]])

In [ ]:
# NAIVE BAYES USING BERNOULLINB METHOD:
from sklearn.naive_bayes import BernoulliNB
kag1 = BernoulliNB()
kag1.fit(x_train, y_train)

BernoulliNB()

In [ ]:
kag1.score(x_test, y_test)

0.9404761904761905

In [ ]:
y_pred = kag1.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm_naive1 = confusion_matrix(y_test, y_pred)
cm_naive1

array([[79,  0],
       [ 5,  0]])

# **DECISION TREE:**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
kag_dtc = DecisionTreeClassifier()
kag_dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
score = kag_dtc.score(x_test, y_test)
score

0.9047619047619048

In [ ]:
y_pred = kag_dtc.predict(x_test)
y_pred

array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm_dt = confusion_matrix(y_test, y_pred)
cm_dt

array([[73,  6],
       [ 2,  3]])